# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=Example/SZDaily.xcworkspace
    - DESTINATION="platform=iOS Simulator,OS=11.3,name=iPhone X"
  matrix:
    - SCHEME="SZDaily-Example"

before_install:
  - gem install xcpretty --no-document --quiet
  - gem install cocoapods --pre --no-document --quiet
  - pod install --project-directory=Example

script:
- set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

